name: Bug report
description: Create a report for something that is broken
labels: ["bug","needs-triage"]
projects: ["stellarbb/4"]

body:
  - type: markdown
    attributes:
      value: |
        This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.

  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: Please give a short description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the behavior and expected behavior
      description: Verbose description

  - type: textarea
    id: files
    attributes:
      label: Attached files
      description: Screenshots, screencasts, dolibarr.log, debugging information
