name: Add Issue to Issue Tracker Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/stellarbb/projects/4
          github-token: ${{ secrets.WORKFLOW_PAT }}
